name: on master

on:
  push:
    branches:
      - master

jobs:
  on_master:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: npm ci 
     - uses: ./
       id: hello
       with:
        welcome-to : man 
     - run: |
        echo "${{ steps.hello.outputs.time }}"
        echo $HELLO
